# view product category
GET http://localhost:5000/category
###

# 1-create product category
POST http://localhost:5000/category
Content-Type: application/json 

{ 
  "title": "watch",
  "parent_id": 3
}
###

# 2-edit product category by name
PUT http://localhost:5000/category/byname
Content-Type: application/json 

{ 
  "oldName": "electronics",
  "newName": "electronics edit"
}
###

# 3-edit product category by id
PUT http://localhost:5000/category/byid
Content-Type: application/json 

{ 
  "id": 1,
  "newName": "electronics"
}
###

# delete product category
DELETE  http://localhost:5000/category/1
###

# 1-deactivate product category
POST http://localhost:5000/category/deactivate/5
Content-Type: application/json 

###